### PR TITLE
lesson 4.5

### PR DESCRIPTION
**Pull request by kmg37**
improved layout and responsiveness

### CODE REVIEW

**Comment by Eightyeightdays** [comment]
- You added a new html page, and renamed the previous index.html to contentPage.html. By default the home page is considered to be index.html, so when I open your code in the browser I see the new page, instead of your work for lesson-4-5.

- The title of you page is practically invisible which is bad for user experience due to the poor contrast ratio. You can download a browser extension called Wave which evaluates and shows accessibility issues on any page, and can help you see errors that you might not even be aware you are making.

- On line 103 of your CSS you set the display style for the `contacts` class then set it to something else on line 107.

- I wasn't able to find where you updated the "Leave a Message" form to use Flexbox or Grid, although you did use it on the labels and input elements.

- For some of your images you've used a `src` attribute that points to an **absolute** file path like: `C:\freyr-intro\css\email-icon.png`. While this may work on your computer it probably won't work on anyone else's due to a different file structure. For example the absolute path to the same file on my computer is: `C:\Users\Utilisateur\Documents\Code The Dream\Student Repos\Kendrick Goedecke\freyr-intro\css\email-icon.png`. Instead, you should use a **relative** file path, where each path is relative to the root folder of your project. In this case freyr-intro is the root folder, so the relative path to that particular file looks like this: `src="./css/email-icon.png"`. Notice how we're also using forward and not backslashes.

- This element in red is currently your fieldMessage div:

kg

As you can see, it stretches across the page, while the other inputs sit next to one another because they have the setting: ` display: inline-block;`. If you want to make the textarea element the same width as the other two combined then you have to target it specifically.
If you set a fixed sized of 350px on the textarea you can make it how you want, except that when you make the screen smaller it won't resize.

Here's an example of how I cut up a page into different boxes in order to get the layout I want:
Sans titre

By wrapping elements in a container that has either a flex-direction of column or row, and then placing them in a main container we can keep the layout flexible while mixing rows and columns.

- To achieve what you want with skills icons instead of words is relatively simple. The only difficult part is finding the code for each icon. If you go to [FontAwesome](https://fontawesome.com/search?o=r&m=free) you can search for free SVG icons that work for this task. 
Once you've found the icon, copy the code snippet: 
js

Then all you have to do is make an array of skillsIcons and append them to the page instead of the original skills list.
Let me know how you get on.

**Comment by kmg37** [comment]
> * You added a new html page, and renamed the previous index.html to contentPage.html. By default the home page is considered to be index.html, so when I open your code in the browser I see the new page, instead of your work for lesson-4-5.
> * The title of you page is practically invisible which is bad for user experience due to the poor contrast ratio. You can download a browser extension called Wave which evaluates and shows accessibility issues on any page, and can help you see errors that you might not even be aware you are making.

Thank you for your insight! I pushed some changes that addressed most of your feedback. As for the 2 points quoted above, I wanted to add a "landing page" of sorts, read that the index file is typically the first to populate so that's why I made a second html file to hold the main lesson code. Should I go ahead and swap them back around for the sake of the assignment(s)?

For the second point, I couldn't figure out which title you were referring to, was thinking maybe text had shown up on top of an image background that hadn't loaded?

**Comment by Eightyeightdays** [comment]
Hi, if you can set it up so that the landing page works and correctly links to the rest of the project I don't see why not.
For the title, I was referring to your name in the header.

**Comment by kmg37** [comment]
> Hi, if you can set it up so that the landing page works and correctly links to the rest of the project I don't see why not. For the title, I was referring to your name in the header.

Thank you. Yeah like you mentioned before, I think the issue was using an absolute file path between the two pages, which I believe was also causing the colors of the links to be thrown off (which included my title as well.) Should hopefully be all good now.

**Comment by Eightyeightdays** [comment]
Yeah, looks good.

**Pull request merged**
